
version: 2

models:
    - name: ASIA_VW
      description: "extract data for ASIA from seed file"

    - name: AFRICA_VW
      description: "extract data for AFRICA from seed file"

    - name: AUSTRALIA_VW
      description: "extract data for AUSTRALIA from seed file"

    - name: AMERICA_VW
      description: "extract data for AMERICA from seed file"

    - name: EUROPE_VW
      description: "extract data for EUROPE from seed file"

    - name: INDIAN_VW
      description: "extract data for INDIAN from seed file"

    - name: PACIFIC_VW
      description: "extract data for PACIFIC from seed file"

    - name: ATLANTIC_VW
      description: "extract data for ATLANTIC from seed file"

    - name: staging_vw
      description: "staging for all the views combined" 
      columns:
          - name: date_witness
            description: " Date of witness sighting "
          - name: witness
            description: "Name of witness sighting the perpetrator"
          - name: agent
            description: "Name of field agent filing the report"
          - name: date_agent
            description: " Date of field agent filing the report"
          - name: city_agent
            description: "HQ city where field agent files the report"
          - name: country
            description: "Country of sighting"
          - name: city
            description: "City of sighting"
          - name: latitude
            description: "Latitude of sighting"
          - name: longitude
            description: "Longitude of sighting"
          - name: has_weapon
            description: "Was the perpetrator observed to be armed?"
          - name: has_hat
            description: "Was the perpetrator wearing a hat?"
          - name: has_jacket
            description: "Was the perpetrator wearing a jacket?"
          - name: behavior
            description: "Short description of perpetrator behavior"
          - name: source_country
            description: "source region of the data published"

    - name: agent
      description: "agent details" 
      columns:
          - name: agent_key
            description: " unique key generated by md5 hash with agent,city_agent,date_agent" 

    - name: witness
      description: "witness details"  
      columns:
          - name: location_id
            description: " unique key generated by md5 hash with country ,city ,latitude ,longitude "   

    - name: region
      description: "region details"   
      columns:
          - name: location_id
            description: " unique key generated by md5 hash with country ,city ,latitude ,longitude " 

    - name: Request1
      description: "Analysis for adhoc request 1"  

    - name: Request2
      description: "Analysis for adhoc request 2"  

    - name: Request3
      description: "Analysis for adhoc request 3" 

    - name: Request4
      description: "Analysis for adhoc request 4" 

